### ISSUE TITLE
Non-ASCII character error

### ISSUE THREAD

**Issue by DHekstra** [ElkeDeZitter/Xtrapol8#28]
hi, I am trying to get Xtrapol8 to run on a linux cluster. After sourcing PHENIX and CCP4, when I try to run Fextr.py, I get the following error:

```
$ phenix.python $GARDEN/Xtrapol8/Fextr.py
Traceback (most recent call last):
  File "/n/hekstra_lab_tier0/Lab/garden//Xtrapol8/Fextr.py", line 102, in <module>
    from calculate_q import calculate_q, outlier_rejection_only
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/Xtrapol8/calculate_q.py", line 27, in <module>
    from Fextr_utils import check_common_indices, make_miller_array
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/Xtrapol8/Fextr_utils.py", line 36, in <module>
    from scipy.stats import linregress
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/phenix/phenix-1.20.1-4487/conda_base/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/phenix/phenix-1.20.1-4487/conda_base/lib/python2.7/site-packages/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/phenix/phenix-1.20.1-4487/conda_base/lib/python2.7/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/n/holylfs05/LABS/hekstra_lab/Lab/garden/phenix/phenix-1.20.1-4487/conda_base/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /n/holylfs05/LABS/hekstra_lab/Lab/garden/phenix/phenix-1.20.1-4487/conda_base/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by ElkeDeZitter** [comment]
Dear DHekstra, thank you very much for reporting this issue.
It is a known bug on Linux systems and Phenix 1.20, and is caused by a unicode issue in scipy v 1.2.0. As Xtrapol8 uses phenix.python and thus the python packages that are shipped with Phenix, the package versions cannot be altered by the user unless by changing Phenix version to version 1.19 (which uses scipy v 1.2.1).

**Comment by DHekstra** [comment]
Thank you, Elke. Reverting to phenix-1.19 did the job.
